### ISSUE TITLE
Duplicate named input causes form posts to have double variables

### ISSUE THREAD

**Issue by imjameshall** [jkosoy/UglyDate#1]
As a user, when I add UglyDate to my form and a user chooses a start date, and end date, the form sends _two_ start date variables.  

I believe this is due to the cloning of the start date to make the pretty view of the chosen date. 

Could we get this "pretty view" to have a different name?

**Comment by jkosoy** [comment]
Fixed in https://github.com/jkosoy/UglyDate/commit/55d7f4237911f511e0d19949dc921155179c4587. This now sets the name of that element to `full-date`. On the server I'd still recommend you use start date and end date, but you have the option of parsing the text there, too.
